title: Yu-Chuan Yu
description: Personal academic homepage of Yu-Chuan Yu.
url: https://yych0303.github.io
baseurl: ""
timezone: Asia/Taipei

markdown: kramdown
collections:
  publications:
    output: false
  news:
    output: false

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - html_source_file
